### ISSUE TITLE
register new IBM i host

### ISSUE THREAD

**Issue by ChrisHird** [IBM/nagios-for-i#10]
I get the following when trying to add a new host

Exception in thread "main" java.lang.NoClassDefFoundError: com/ibm/as400/access/AS400
        at com.ibm.nagios.config.HostConfig.Insert(HostConfig.java:113)
        at com.ibm.nagios.config.HostConfig.main(HostConfig.java:82)
Caused by: java.lang.ClassNotFoundException: com.ibm.as400.access.AS400
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 2 more

New install of nagios from ova and followed instructions for installing the plugin.

**Comment by ChrisHird** [comment]
Problem was caused by incorrect installation of Nagios Plugins into Nagios XI where should have used the wizards.

**Comment by carldavis** [comment]
Can you provide any further info about this? I don't have XI and am getting this error.

**Comment by sgatepunk** [comment]
I am having the same issue.  Not running XI.

**Comment by sgatepunk** [comment]
Had success after adding all of the jar file to the classpath instead of just the nagios4i one. i.e.:

 java -cp /usr/local/nagios/libexec/nagios4i.jar:/usr/local/nagios/libexec/jt400.jar:/usr/local/nagios/libexec/gson.jar com.ibm.nagios.config.HostConfig -i host
